### ISSUE TITLE
如何在docker 中找回进程

### ISSUE THREAD

**Issue by mocker12345** [WangYihang/GitHacker#12]
您好，我用docker 运行 githacker，githacker 一般要运行很久。我退出容器 或者 退出 主机ssh，我再次进入容器时，怎么找回githacker的进程，查看他的运行情况。

```
docker attach
```

ctrl+p+q

**Comment by WangYihang** [comment]
另外可以通过 `--threads` 设置线程数量来提高速度（如果目标网站对请求速率没有限制的话）。

**Comment by mocker12345** [comment]
下着下着 就Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,

以后可否增加代理配置

**Comment by mocker12345** [comment]
一个目标下载不完 被目标'Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) ,这种情况下，是否可能 续传？

**Comment by WangYihang** [comment]
> 下着下着 就Exception in thread Thread-14:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
> chunked=chunked,
> 
> 以后可否增加代理配置

代理请使用 `proxychains`。

**Comment by WangYihang** [comment]
> 一个目标下载不完 被目标'Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) ,这种情况下，再次启动是会检测已经下载的吗？

会，如果你觉得这次没有下载完整，就重新运行直到所有 Objects 都下载成功。

**Comment by WangYihang** [comment]
为了能够尽可能复现你的环境，如果方便的话，是否可以提供目标网站的地址？@mocker12345

**Comment by WangYihang** [comment]
另外，请在一个 Issue 中只讨论一件事情。

**Comment by mocker12345** [comment]
> > 一个目标下载不完 被目标'Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) ,这种情况下，再次启动是会检测已经下载的吗？
> 
> 会，如果你觉得这次没有下载完整，就重新运行直到所有 Objects 都下载成功。
> 后续会添加：自动将下载失败的 Objects 重新加入队列。

重新下载 也会再次请求大量404的object，到一定请求数量还是会被目标ban掉，目标文件比较多的话 永远下不完 -_-

**Comment by WangYihang** [comment]
大量的 404 是因为目标的 Git 仓库存在 packed files，目前还不支持对 packed files 的下载。
如果下载是 404，记录当前 hash 并没有用，因为这个 object 文件在 packed files 里。

**Comment by WangYihang** [comment]
没有目标网站，我无法复现你的情况。

**Comment by mocker12345** [comment]
> 没有目标网站，我无法复现你的情况。

师傅，check gmail
