### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode

### ISSUE THREAD

**Issue by websecer** [WangYihang/GitHacker#14]
Traceback (most recent call last):
  File "/usr/local/bin/githacker", line 11, in <module>
    load_entry_point('GitHacker==1.0.2', 'console_scripts', 'githacker')()
  File "/usr/local/lib/python3.8/dist-packages/GitHacker-1.0.2-py3.8.egg/GitHacker/__init__.py", line 265, in main
  File "/usr/local/lib/python3.8/dist-packages/GitHacker-1.0.2-py3.8.egg/GitHacker/__init__.py", line 45, in start
  File "/usr/local/lib/python3.8/dist-packages/GitHacker-1.0.2-py3.8.egg/GitHacker/__init__.py", line 197, in add_blob_file_tasks
  File "/home/romanee/.local/lib/python3.8/site-packages/git/index/base.py", line 441, in iter_blobs
    for entry in self.entries.values():
  File "/home/romanee/.local/lib/python3.8/site-packages/gitdb/util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "/home/romanee/.local/lib/python3.8/site-packages/git/index/base.py", line 128, in _set_cache_
    self._deserialize(stream)
  File "/home/romanee/.local/lib/python3.8/site-packages/git/index/base.py", line 157, in _deserialize
    self.version, self.entries, self._extension_data, _conten_sha = read_cache(stream)
  File "/home/romanee/.local/lib/python3.8/site-packages/git/index/fun.py", line 198, in read_cache
    path = read(path_size).decode(defenc)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 0: invalid start byte

系统环境
ubuntu20
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
python 3.8
git version 2.25.1

**Comment by websecer** [comment]
ourbest0#gmail.com 这个给我发个邮件把

**Comment by websecer** [comment]
麻烦老哥发个邮件b3VyYmVzdDAjZ21haWwuY29t

**Comment by WangYihang** [comment]
- [ ] 测试通过任意文件读取漏洞来获取目标仓库

**Comment by WangYihang** [comment]
我这边测试通过任意文件**读取**是可以正常利用的，参见 `test.py`。
如果是任意文件包含，则情况比较复杂，很难利用，得具体情况具体分析，提取出被包含的文件的具体内容再一点一点恢复。

**Comment by WangYihang** [comment]
你这个遇到的 `'utf-8' codec can't decode byte 0x96 in position 0: invalid start byte`，我复现不出来，暂时无法调试。
